name: CI Workflow     # Workflow name 
 
on: [push]            # Triggered on every push 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - run: sleep 5

      - run: echo "Building the project"
  